// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package management

type AppendResult struct {
	Pos int `json:"pos"`
}

type Message struct {
	StreamID string `json:"streamId"`
	Header   string `json:"header"`
	Value    string `json:"value"`
}

type MessageInput struct {
	Header *string `json:"header"`
	Value  *string `json:"value"`
}

type MessagesResult struct {
	From     int       `json:"from"`
	Messages []Message `json:"messages"`
	Next     *int      `json:"next"`
	Previous *int      `json:"previous"`
}
